spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rest_with_spring_boot_arthur?useTimezone=true&serverTimezone=UTC
    username: arthur
    password: db1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      properties:
        hibernate.format_sql: true
        hibernate.generate_statistics: true
      logging:
        level:
          org.hibernate.stat: debug